title:              Dohyun Blog
email:              happydhKim870@gmail.com
description:        Dohyun's thinking Blog
author:             Dohyun Kim
baseurl:            ""
url:                "https://happydhKim.github.io"

# Social Profiles
twitter_username:   
github_username:    happydhKim
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
